# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group_message',
            fields=[
                ('gm_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField(max_length=100)),
                ('photo_url', models.URLField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('photo_url', models.URLField(max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserIsAdminGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserIsGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserReceivesGroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('gm_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group_message')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSendsGroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('gm_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group_message')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersendsgroupmessage',
            unique_together=set([('phone_number', 'gm_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='userreceivesgroupmessage',
            unique_together=set([('phone_number', 'gm_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='userisgroupmember',
            unique_together=set([('g_id', 'phone_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='userisadmingroup',
            unique_together=set([('g_id', 'phone_number')]),
        ),
    ]
