# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('gm_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField(max_length=100)),
                ('photo_url', models.URLField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesInTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_checkin_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Places')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_review', models.CharField(max_length=1000)),
                ('trip_start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip_end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserIsAdminGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserIsGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserReceivesGroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('gm_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.GroupMessage')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSendsGroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Group')),
                ('gm_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.GroupMessage')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='placesintrip',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Trip'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrips',
            unique_together=set([('phone_number', 'trip_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='usersendsgroupmessage',
            unique_together=set([('phone_number', 'gm_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='userreceivesgroupmessage',
            unique_together=set([('phone_number', 'gm_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='userisgroupmember',
            unique_together=set([('g_id', 'phone_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='userisadmingroup',
            unique_together=set([('g_id', 'phone_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesintrip',
            unique_together=set([('trip_id', 'place_id')]),
        ),
    ]
