# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('place_geo_location', models.CharField(max_length=100)),
                ('place_description', models.CharField(max_length=1000)),
                ('place_reviews', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesInTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_checkin_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('place_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Places')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_review', models.CharField(max_length=1000)),
                ('trip_start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip_end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.User')),
                ('trip_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='placesintrip',
            name='trip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Trip'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrips',
            unique_together=set([('phone_number', 'trip_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesintrip',
            unique_together=set([('trip_id', 'place_id')]),
        ),
    ]
