# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160404_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='places',
            name='place_description',
        ),
        migrations.RemoveField(
            model_name='places',
            name='place_geo_location',
        ),
        migrations.RemoveField(
            model_name='places',
            name='place_reviews',
        ),
        migrations.AlterField(
            model_name='places',
            name='place_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placesintrip',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Places'),
        ),
        migrations.AlterField(
            model_name='placesintrip',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Trip'),
        ),
        migrations.AlterField(
            model_name='usertrips',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.User'),
        ),
        migrations.AlterField(
            model_name='usertrips',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Trip'),
        ),
        migrations.AddField(
            model_name='test',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Places'),
        ),
        migrations.AddField(
            model_name='test',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Trip'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set([('trip_id', 'place_id')]),
        ),
    ]
