# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160411_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_message',
            new_name='GroupMessage',
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='test',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='userisgroupmember',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userisgroupmember',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
