# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userisgroupmember',
            name='latitude',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='userisgroupmember',
            name='longitude',
            field=models.CharField(default='0.0', max_length=10),
        ),
    ]
