# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160422_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_id',
        ),
    ]
