# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160424_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
