# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160422_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userisadmingroup',
            name='g_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Group'),
        ),
        migrations.AlterField(
            model_name='userisadmingroup',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.User'),
        ),
        migrations.AlterField(
            model_name='userisgroupmember',
            name='g_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Group'),
        ),
        migrations.AlterField(
            model_name='userisgroupmember',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.User'),
        ),
        migrations.AlterField(
            model_name='userreceivesgroupmessage',
            name='g_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Group'),
        ),
        migrations.AlterField(
            model_name='userreceivesgroupmessage',
            name='gm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.GroupMessage'),
        ),
        migrations.AlterField(
            model_name='userreceivesgroupmessage',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.User'),
        ),
        migrations.AlterField(
            model_name='usersendsgroupmessage',
            name='g_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Group'),
        ),
        migrations.AlterField(
            model_name='usersendsgroupmessage',
            name='gm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.GroupMessage'),
        ),
        migrations.AlterField(
            model_name='usersendsgroupmessage',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.User'),
        ),
    ]
