# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_user_reg_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreceivesgroupmessage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userreceivesgroupmessage',
            name='g_id',
        ),
        migrations.RemoveField(
            model_name='userreceivesgroupmessage',
            name='gm_id',
        ),
        migrations.RemoveField(
            model_name='userreceivesgroupmessage',
            name='phone_number',
        ),
        migrations.AlterUniqueTogether(
            name='usersendsgroupmessage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usersendsgroupmessage',
            name='g_id',
        ),
        migrations.RemoveField(
            model_name='usersendsgroupmessage',
            name='gm_id',
        ),
        migrations.RemoveField(
            model_name='usersendsgroupmessage',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='UserReceivesGroupMessage',
        ),
        migrations.DeleteModel(
            name='UserSendsGroupMessage',
        ),
    ]
