# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20160422_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userisgroupmember',
            name='latitude',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='userisgroupmember',
            name='longitude',
            field=models.CharField(default='0.0', max_length=10),
        ),
    ]
